### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by constantingoeldel**
With this pull request, all displayed data is stored online with MongoDB atlas, evaluated in my backend https://github.com/constantingoeldel/unfinished-api, which is hosted by Heroku. The goal of this story was therefore to uphold the previous functionality as no new features for the user were added, but to also increase code quality. A review is much appreciated :)

### CODE REVIEW

**Review by ninasander — APPROVED** [review]
Nice work! :) The logic itself looks good to me, but maybe it's better for the readability of the code to declare the proptypes at the top of your code, before your component function. But I also understand if you consider it to be more readable when the proptypes are at the bottom of your code, considering how long some of your proptype declarations are.

**Comment by constantingoeldel** [comment]
> considering how long some of your proptype declarations are.

That is the primary reason they're not at the top, might change it for the smaller ones, though

**Comment by carolinwagner** [comment]
QA: ✅ 
Filter as well as search function are working great and projects are shown correctly! And btw I really like the way a user can choose the filter options :-)

**Comment by constantingoeldel** [comment]
Thanks for the review 🥇

**Pull request merged**
